<div class="panel panel-transparent">
    <div class="panel-heading">
        <div class="pull-right">
            <div class="col-xs-12">
                <a href="<?= $this->url('user/add')?>" id="add-club" class="btn btn-primary btn-cons">
                    <i class="fa fa-plus"></i> <?=$this->translate('__label_user_add')?></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="panel-body">
        <div id="tableWithDynamicRows_wrapper" class="dataTables_wrapper form-inline no-footer"><div class="table-responsive">
                <table id="clubs-table" class="table table-hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th><?=$this->translate('__label_id')?></th>
                        <th><?=$this->translate('__user_first_name')?></th>
                        <th><?=$this->translate('__user_last_name')?></th>
                        <th><?=$this->translate('__user_age')?></th>
                        <th><?=$this->translate('__user_sex')?></th>
                        <th><?=$this->translate('__user_size')?></th>
                        <th><?=$this->translate('__user_ski_level')?></th>
                        <th><?=$this->translate('__label_action')?></th>
                    </tr>
                    </thead>

                    <tfoot>
                    <tr>
                        <th><?=$this->translate('__label_id')?></th>
                        <th><?=$this->translate('__user_first_name')?></th>
                        <th><?=$this->translate('__user_last_name')?></th>
                        <th><?=$this->translate('__user_age')?></th>
                        <th><?=$this->translate('__user_sex')?></th>
                        <th><?=$this->translate('__user_size')?></th>
                        <th><?=$this->translate('__user_ski_level')?></th>
                        <th><?=$this->translate('__label_action')?></th>
                    </tr>
                    </tfoot>

                    <tbody>

                    <?php

                    /**@var  \Application\Entity\User $user */
                    foreach($this->users as $user)
                    {
                        ?>

                        <tr>
                            <td><?=$user->getId()?></td>
                            <td><?=$user->getFirstName()?></td>
                            <td><?=$user->getLastName()?></td>
                            <td><?=$user->getAge()?></td>
                            <td><?=$user->getSex()?></td>
                            <td><?=$user->getSize()?></td>
                            <td><?=$user->getSkiLevel()->getName()?></td>
                            <td>
                                <div class="btn-group">
                                    <a href="<?=$this->url('user/edit',array('ski_level_id'=>$user->getId()))?>" type="button"
                                       class="btn btn-default" data-toggle="tooltip" data-placement="top"
                                       title="<?=$this->translate('__label_ski_level_edit')?>"><i class="fa fa-pencil"></i>
                                    </a>
                                    <a href="<?=$this->url('user/delete',array('ski_level_id'=>$user->getId()))?>" type="button"
                                       class="btn btn-default" data-toggle="tooltip" data-placement="top"
                                       title="<?=$this->translate('__label_ski_level_delete')?>"><i class="fa fa-trash-o"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <?php
                    }
                    ?>

                    </tbody>
                </table>
            </div>
        </div>

