<?php
/** @var \Application\Form\Ski $form */
$form = $this->form;
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<div class="row">
    <div class=" col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10">
        <div class="form-group form-group-default required"">
        <?= $this->formLabel($form->get('name')); ?>
        <?= $this->formElement($form->get('name')); ?>
        <span class="help-block errors"><?= $this->formElementErrors($form->get('name')); ?></span>
        </div>
    </div>
</div>
<div class="row">
    <div class=" col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10">
        <div class="form-group form-group-default">
            <?= $this->formLabel($form->get('length')); ?>
            <?= $this->formElement($form->get('length')); ?>
            <span class="help-block errors"><?= $this->formElementErrors($form->get('length')); ?></span>
        </div>
    </div>
</div>
<div class="row">
    <div class=" col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8 col-xs-offset-1 col-xs-10">
        <div class="form-group form-group-default required">
            <?= $this->formLabel($form->get('isNew')); ?>
            <?= $this->formCheckbox($form->get('isNew')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-offset-2 col-lg-4 col-md-offset-2 col-md-4 col-sm-offset-2 col-sm-4 col-xs-offset-1 col-xs-10">
        <?= $this->formElement($form->get('submit')->setValue('__label_save_ski')); ?>
    </div>
</div>